---
- include_role:
    name: package
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
- import_tasks: key.yml
- import_tasks: repo.yml
- include_role:
    name: package
