---
- name: ensure docker and docker-compose packages
  include_role:
    name: "damex.package"
  vars:
    package_packages:
      - name: "{{ docker_package_name }}"
        version: "{{ docker_package_version }}"
        state: "{{ docker_package_state }}"
      - name: "{{ docker_compose_package_name }}"
        version: "{{ docker_compose_package_version }}"
        state: "{{ docker_compose_package_state }}"
