---
- name: ensure systemd service
  include_role:
    name: "damex.systemd_service"
  vars:
    systemd_service_name: "{{ docker_service_name }}"
    systemd_service_restart_on: "docker_daemon_json.changed"
